config/routes.rb
Rails.application.routes.draw do
  resources :res
  resources :items
  resources :post_comments
  resources :posts
  get 'users/show'
  get 'static_pages/home'
  root to: 'static_pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/re.rb
class Re < ApplicationRecord
    has_one_attached :image
    has_many :posts, -> { order "created_at DESC"}
    has_many :items, dependent: :destroy
end

app/controllers/res_controller.rb
class ResController < ApplicationController
  before_action :set_re, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /res
  # GET /res.json
  def index
    @res = Re.all
  end

  # GET /res/1
  # GET /res/1.json
  def show
    @re = Re.find(params[:id])
    @item = Item.new
  end

  # GET /res/new
  def new
    @re = Re.new
  end

  # GET /res/1/edit
  def edit
  end

  # POST /res
  # POST /res.json
  def create
    @re = Re.new(re_params)

    respond_to do |format|
      if @re.save
        format.html { redirect_to @re, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @re }
      else
        format.html { render :new }
        format.json { render json: @re.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /res/1
  # PATCH/PUT /res/1.json
  def update
    respond_to do |format|
      if @re.update(re_params)
        format.html { redirect_to @re, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @re }
      else
        format.html { render :edit }
        format.json { render json: @re.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /res/1
  # DELETE /res/1.json
  def destroy
    @re.destroy
    respond_to do |format|
      format.html { redirect_to res_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_re
      @re = Re.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def re_params
      params.require(:re).permit(:name, :address)
      params.require(:re).permit(:name, :address, :image)
    end
end

app/helpers/res_helper.rb
module ResHelper
end

app/views/res/_form.html.erb
<%= form_with(model: re, local: true) do |form| %>
  <% if re.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(re.errors.count, "error") %> prohibited this re from being saved:</h2>

      <ul>
        <% re.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  
  <div class="field">
     <%= form.label :image %>
     <%= form.file_field :image %><br>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/res/edit.html.erb
<h1>Editing Re</h1>

<%= render 'form', re: @re %>

<%= link_to 'Show', @re %> |
<%= link_to 'Back', res_path %>

app/views/res/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your list restaurant</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @res.each do |re| %>
      <tr>
        <td><%= re.name %></td>
        <td><%= re.address %></td>
        <td><%= link_to 'Show', re %></td>
        <td><%= link_to 'Edit', edit_re_path(re) %></td>
        <td><%= link_to 'Delete', re, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add new restaurant', new_re_path %>

app/views/res/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', re: @re %>

<%= link_to 'Back', res_path %>

app/views/res/show.html.erb
<p id="notice"><%= notice %></p>

<p>
   <% if @re.image.attached? %>
     <%= image_tag @re.image %>
   <% end %>
</p>
 
<p>
  <strong>Name:</strong>
  <%= @re.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @re.address %>
</p>

<p>
  <strong>Related Post:</strong>
  <% Post.all.each do |post|%>
    <% if post.res_id == @re.id %>
      <li>
        <%= link_to post.title, post_path %> (<i><%= post.user.name %></i>)
      </li>
    <% end %>
  <% end %>
</p>

<p>
  <strong>Menu:</strong>
  <% Item.all.each do |item|%>
    <% if item.res_id == @re.id %>
      <li>
        <%= link_to item.name, item_path(item.id) %> (<i><%= item.price %>ドン</i>)
      </li>
    <% end %>
  <% end %>
  <br>
  <%= link_to 'Add new item?', new_item_path(@re.id) %>
</p>

<hr>

<%= link_to 'Edit', edit_re_path(@re) %> |
<%= link_to 'Back', res_path %>