config/routes.rb
Rails.application.routes.draw do
  resources :res
  resources :items
  resources :post_comments
  resources :posts
  get 'users/show'
  get 'static_pages/home'
  root to: 'static_pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    has_many :post_comment, -> { order "created_at DESC"}
    belongs_to :re, :optional => true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_re, only: [:index, :show, :edit, :update]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_comment = PostComment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
    
    def set_re
      @res = Re.all
    end
    
    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :res_id, :title, :detail, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong>User: <%= link_to current_user.name, users_show_path %></strong>
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="field">
    <%= form.label :res_id %>
    <%= form.collection_select :res_id, Re.order(:name), :id, :name, include_blank: false %>
  </div>
  
 
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<% if @posts[0] != nil then %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>User</th>
        <th>Restaurant</th>
        <th>Post title</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.user.name %></td>
          <td><%= link_to @res[post.res_id - 1].name, re_path(post.res_id) %> </td>
          <td><%= post.title %> </td>
          <td><%= link_to 'Show', post %></td>
          <% if post.user.name == current_user.name %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <p>No posts at the moment!!! Create one?</p>
  <p>↓</p>
<% end %>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<p>
  <strong>Res:</strong>
  <%= @res[@post.res_id - 1].name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @post.detail %>
</p>

<p>
  <% if @post.image.attached? %>
    <%= image_tag @post.image %>
  <% end %>
</p>

<h2>Comment Form</h2>
 <%= form_with(model: @post_comment, local: true) do |form| %>
   <div class= "field">
     <%= form.text_area :comment %>
     <%= form.hidden_field :post_id, :value => @post.id %>
     <%= form.hidden_field :user_id, :value => current_user.id %>
   </div>
   <div class="actions">
     <%= form.submit %>
   </div>
<% end %>

<h2>List comment</h2>
    <ul>
       <% @post.post_comment.each do |each_comment|%>
        <li><%= each_comment.comment %>
          (<i><%= each_comment.user.name %></i>)
          <% if current_user.name == each_comment.user.name %>
          <td><%= link_to 'Edit', edit_post_comment_path(each_comment) %></td> |
          <td><%= link_to 'Destroy', each_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </li>
      <% end %>
    </ul>

<% if @post.user.name == current_user.name %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>